/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'BadNews' at '11.07.16 14:49' with Gradle 2.13
 *
 * @author BadNews, @date 11.07.16 14:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
